Link_globalPay/cartridges/int_globalpay_sfra/cartridge/templates/default/checkout/billing/globalpaycreditcards.isml
=> Signed-off-by: Nevil Alexander Pereira <m1067575@mindtree.com>

Link_globalPay/cartridges/int_globalpay/cartridge/scripts/dtos/paymentMethods/DeletePaymentTokenization.js, Link_globalPay/cartridges/int_globalpay/cartridge/scripts/dtos/paymentMethods/PaymentTokenization.js, Link_globalPay/cartridges/int_globalpay/cartridge/scripts/helpers/globalPayHelper.js, Link_globalPay/cartridges/int_globalpay_sfra/cartridge/controllers/PaymentInstruments.js, Link_globalPay/cartridges/int_globalpay_sfra/cartridge/scripts/hooks/payment/processor/globalpaycredit.js
Tokenize and Detokenization Chnages
=> Tokenize and Detokenize Creditcard Token

Link_globalPay/cartridges/int_globalpay/cartridge/scripts/dtos/Refund.js, Link_globalPay/cartridges/int_globalpay/cartridge/scripts/helpers/globalPayHelper.js, Link_globalPay/cartridges/int_globalpay/cartridge/scripts/helpers/globalPayPreferences.js, Link_globalPay/cartridges/int_globalpay_sfra/cartridge/controllers/OrderTransactions.js, Link_globalPay/cartridges/int_globalpay_sfra/cartridge/controllers/PaymentInstruments.js, Link_globalPay/cartridges/int_globalpay_sfra/cartridge/scripts/middleware/security.js, Link_globalPay/cartridges/int_globalpay_sfra/cartridge/templates/resources/globalpay.properties
Refund and Capture Chnages.. Need to add one custom attribute to the sitePerefernce to save Client ID: 
Custom Attribute ID : "gp_clientID"
Value: 4230946d-3f35-4e91-8303-a51720ba7a5b
=> Globalpay capture and refund

Link_globalPay/cartridges/int_globalpay/cartridge/scripts/helpers/globalPayHelper.js, Link_globalPay/cartridges/int_globalpay_sfra/cartridge/controllers/OrderTransactions.js
=> Refund and Capture Bug Fixes

Link_globalPay/cartridges/int_globalpay_sfra/cartridge/controllers/CheckoutServices.js, Link_globalPay/cartridges/int_globalpay_sfra/cartridge/scripts/hooks/payment/processor/globalpaygooglepay.js
=> changes for error handling

Link_globalPay/cartridges/int_globalpay_controllers/cartridge/forms/default/creditcard.xml, Link_globalPay/cartridges/int_globalpay_controllers/cartridge/scripts/payment/processor/GOOGLE_PAY.js, Link_globalPay/cartridges/int_globalpay_controllers/cartridge/static/default/js/googlepay.js, Link_globalPay/cartridges/int_globalpay_controllers/cartridge/templates/default/checkout/billing/paymentmethods.isml
code changes for Gpay token fix
=> code changes for Gpay token fix

Link_globalPay/cartridges/int_globalpay/cartridge/scripts/helpers/globalPayPreferences.js, Link_globalPay/cartridges/int_globalpay_sfra/cartridge/client/default/js/googlepay/googlepay.js, Link_globalPay/cartridges/int_globalpay_sfra/cartridge/controllers/Checkout.js, Link_globalPay/cartridges/int_globalpay_sfra/cartridge/templates/default/checkout/checkout.isml
A site preference need to be added ID: 'gatewayMerchantId'   Value : 'gpapiqa1'
=> -------------passing gatewayMerchantId dynamically SFRA---------------

Link_globalPay/cartridges/int_globalpay_controllers/cartridge/controllers/COBilling.js, Link_globalPay/cartridges/int_globalpay_controllers/cartridge/forms/default/creditcard.xml, Link_globalPay/cartridges/int_globalpay_controllers/cartridge/scripts/constants/globalpayconstants.js, Link_globalPay/cartridges/int_globalpay_controllers/cartridge/scripts/payment/processor/GLOBAL_PAY_CREDIT.js, Link_globalPay/cartridges/int_globalpay_controllers/cartridge/templates/default/checkout/billing/globalpaycreditcards.isml, Link_globalPay/cartridges/int_globalpay_controllers/cartridge/templates/default/checkout/billing/paymentmethods.isml, Link_globalPay/cartridges/int_globalpay_controllers/cartridge/templates/default/checkout/globalpay/threeds.isml
=> changes for 3d secure in SG

Link_globalPay/cartridges/int_globalpay_sfra/cartridge/controllers/CheckoutServices.js, Link_globalPay/cartridges/int_globalpay_sfra/cartridge/scripts/constants/globalpayconstants.js, Link_globalPay/cartridges/int_globalpay_sfra/cartridge/scripts/hooks/payment/processor/globalpaygooglepay.js
google pay error code handling
=> google pay error code handling

Link_globalPay/cartridges/int_globalpay_controllers/cartridge/controllers/COPlaceOrder.js, Link_globalPay/cartridges/int_globalpay_controllers/cartridge/scripts/payment/processor/PAYPAL_EXPRESS.js
changes for paypal capture in SG
=> changes for paypal capture in SG

Link_globalPay/cartridges/int_globalpay_controllers/cartridge/static/default/css/paymentbuttons.css, Link_globalPay/cartridges/int_globalpay_controllers/cartridge/templates/default/checkout/billing/applePayForm.isml, Link_globalPay/cartridges/int_globalpay_controllers/cartridge/templates/default/checkout/billing/globalpaycreditcards.isml, Link_globalPay/cartridges/int_globalpay_controllers/cartridge/templates/default/checkout/billing/paypalForm.isml
66-paypal and apple pay button change in SG
72-Valid spelling fix in SG
=> Bug Defect fix for 66 and 72

Link_globalPay/cartridges/int_globalpay_controllers/cartridge/forms/default/creditcard.xml
=> card expiry year issue

Link_globalPay/cartridges/int_globalpay/cartridge/templates/default/checkout/billing/paymentOptions/googlePayForm.isml, Link_globalPay/cartridges/int_globalpay_controllers/cartridge/controllers/COBilling.js, Link_globalPay/cartridges/int_globalpay_controllers/cartridge/controllers/COPlaceOrder.js, Link_globalPay/cartridges/int_globalpay_controllers/cartridge/controllers/COSummary.js, Link_globalPay/cartridges/int_globalpay_controllers/cartridge/scripts/payment/processor/GLOBAL_PAY_CREDIT.js, Link_globalPay/cartridges/int_globalpay_controllers/cartridge/scripts/payment/processor/GOOGLE_PAY.js, Link_globalPay/cartridges/int_globalpay_controllers/cartridge/scripts/payment/processor/PAYPAL_EXPRESS.js, Link_globalPay/cartridges/int_globalpay_controllers/cartridge/static/default/js/paypal.js, Link_globalPay/cartridges/int_globalpay_controllers/cartridge/templates/default/checkout/billing/paymentmethods.isml
code changes for saved card issues
=> code changes for saved card issues

Link_globalPay/cartridges/int_globalpay/cartridge/scripts/constants/globalpayconstants.js, Link_globalPay/cartridges/int_globalpay_controllers/cartridge/controllers/COPlaceOrder.js, Link_globalPay/cartridges/int_globalpay_controllers/cartridge/scripts/payment/processor/GLOBAL_PAY_CREDIT.js
=> changes for bugfix-63

Link_globalPay/cartridges/int_globalpay_sfra/cartridge/scripts/hooks/payment/processor/globalpaycredit.js, Link_globalPay/cartridges/int_globalpay_sfra/cartridge/scripts/hooks/payment/processor/globalpaygooglepay.js, Link_globalPay/cartridges/int_globalpay_sfra/cartridge/scripts/hooks/payment/processor/globalpaypaypal.js
Bug Fix for 85,88,89,90
removed payment instruments in hooks and will able to see only one transaction id
=> Bug fix24 feb

Link_globalPay/cartridges/int_globalpay_sfra/cartridge/scripts/hooks/payment/processor/globalpaygooglepay.js
=> Bug Fix 90

Link_globalPay/cartridges/int_globalpay_controllers/cartridge/static/default/css/global-pay.css, Link_globalPay/cartridges/int_globalpay_sfra/cartridge/scripts/hooks/payment/processor/globalpaycredit.js, Link_globalPay/cartridges/int_globalpay_sfra/cartridge/scripts/hooks/payment/processor/globalpaygooglepay.js, Link_globalPay/cartridges/int_globalpay_sfra/cartridge/scripts/hooks/payment/processor/globalpaypaypal.js
=> Bug Fix-88,90

Link_globalPay/cartridges/int_globalpay_controllers/cartridge/scripts/payment/processor/GLOBAL_PAY_CREDIT.js
Changed the condition on getting result of authorization just like sfra hook
=> Bug Fix 87

Link_globalPay/cartridges/int_globalpay_sfra/cartridge/templates/default/checkout/billing/paymentOptions/applePayTab.isml, Link_globalPay/cartridges/int_globalpay_sfra/cartridge/templates/default/checkout/billing/paymentOptions/googlePayTab.isml, Link_globalPay/cartridges/int_globalpay_sfra/cartridge/templates/default/checkout/billing/paymentOptions/paypalTab.isml
=> Apple Pay Tab Alignment Issue

Link_globalPay/cartridges/int_globalpay_sfra/cartridge/client/default/js/checkout/checkout.js, Link_globalPay/cartridges/int_globalpay_sfra/cartridge/client/default/js/checkout/threeds.js, Link_globalPay/cartridges/int_globalpay_sfra/cartridge/controllers/Checkout.js, Link_globalPay/cartridges/int_globalpay_sfra/cartridge/controllers/GlobalPay.js, Link_globalPay/cartridges/int_globalpay_sfra/cartridge/controllers/OrderTransactions.js, Link_globalPay/cartridges/int_globalpay_sfra/cartridge/controllers/PaymentInstruments.js, Link_globalPay/cartridges/int_globalpay_sfra/cartridge/scripts/checkout/checkoutHelpers.js, Link_globalPay/cartridges/int_globalpay_sfra/cartridge/scripts/hooks/payment/globalpayapplepay.js, Link_globalPay/cartridges/int_globalpay_sfra/cartridge/scripts/hooks/payment/processor/globalpaycredit.js, Link_globalPay/cartridges/int_globalpay_sfra/cartridge/scripts/hooks/payment/processor/globalpaypaypal.js, Link_globalPay/cartridges/int_globalpay_sfra/cartridge/scripts/utils/PaymentInstrumentUtils.js
=> Code Alignment and code comment

Link_globalPay/cartridges/int_globalpay_sfra/cartridge/scripts/hooks/payment/globalpayapplepay.js, Link_globalPay/cartridges/int_globalpay_sfra/cartridge/scripts/hooks/payment/processor/globalpaycredit.js, Link_globalPay/cartridges/int_globalpay_sfra/cartridge/scripts/hooks/payment/processor/globalpaygooglepay.js, Link_globalPay/cartridges/int_globalpay_sfra/cartridge/scripts/hooks/payment/processor/globalpaypaypal.js
=> Removed unwanted code and variables

Link_globalPay/cartridges/int_globalpay/cartridge/scripts/util/PaymentInstrumentUtils.js, Link_globalPay/cartridges/int_globalpay/cartridge/scripts/util/creditcardutils.js, Link_globalPay/cartridges/int_globalpay_controllers/cartridge/forms/default/creditcard.xml, Link_globalPay/cartridges/int_globalpay_controllers/cartridge/templates/default/checkout/billing/paymentmethods.isml, Link_globalPay/cartridges/int_globalpay_sfra/cartridge/controllers/CheckoutServices.js, Link_globalPay/cartridges/int_globalpay_sfra/cartridge/controllers/Order.js, Link_globalPay/cartridges/int_globalpay_sfra/cartridge/controllers/PaymentInstruments.js, Link_globalPay/cartridges/int_globalpay_sfra/cartridge/forms/default/creditCard.xml, Link_globalPay/cartridges/int_globalpay_sfra/cartridge/scripts/hooks/payment/processor/globalpaycredit.js, Link_globalPay/cartridges/int_globalpay_sfra/cartridge/scripts/hooks/payment/processor/globalpaygooglepay.js, Link_globalPay/cartridges/int_globalpay_sfra/cartridge/scripts/hooks/payment/processor/globalpaypaypal.js, Link_globalPay/cartridges/int_globalpay_sfra/cartridge/templates/default/checkout/billing/creditCardForm.isml, Link_globalPay/cartridges/int_globalpay_sfra/cartridge/templates/default/checkout/billing/globalpaycreditcards.isml
=> Code Refactoring
